# -*- coding: utf-8 -*-
"""Atividade02-Questao-08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j0hvzVyuzpt4bFK7J-LkS4ZExeCHTSv

8. Utilizando pandas, como realizar a leitura de um arquivo CSV em um
DataFrame e exibir as primeiras linhas?
"""

df = pd.read_csv('arquivo.csv')
df.head()