# -*- coding: utf-8 -*-
"""Atividade02-Questao-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j0hvzVyuzpt4bFK7J-LkS4ZExeCHTSv

10.Utilizando pandas, como lidar com valores ausentes (NaN) em um
DataFrame?
"""

import pandas as pd


df = pd.read_csv('dados.csv')
df.isna().sum()
df.dropna()

# Preencher com média
df['coluna'] = df['coluna'].fillna(df['coluna'].mean())

# Preencher com mediana
df['coluna'] = df['coluna'].fillna(df['coluna'].median())

# Preencher com valor fixo
df.fillna(0)