# -*- coding: utf-8 -*-
"""Atividade02-Questao-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j0hvzVyuzpt4bFK7J-LkS4ZExeCHTSv

9. Utilizando pandas, como selecionar uma coluna específica e filtrar linhas
em um “DataFrame” com base em uma condição?
"""

import pandas as pd

data = {'Pessoa': ['João', 'Maria', 'Pedro', 'Ana'],
        'Idade': [25, 30, 35, 30]}

df = pd.DataFrame(data)

filtro = df[df['Idade'] >= 30]
print(filtro)