# -*- coding: utf-8 -*-
"""Atividade02-Questao-07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18j0hvzVyuzpt4bFK7J-LkS4ZExeCHTSv

7. Como concatenar vários DataFrames (empilhando linhas ou colunas),
mesmo que tenham colunas diferentes?
Dica: Utiliza-se pd.concat() especificando axis=0 (linhas) ou axis=1
(colunas). Quando há colunas diferentes, os valores ausentes são
preenchidos com NaN.
"""

pd.concat([df1, df2], axis=0)